version: '3'

volumes:
  sf-payments-mysql-data:
    driver: local

networks:
  sf-payments:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    container_name: nginx-sf-payments
    depends_on:
      - php
    volumes:
      - './src:/var/www/html'
    ports:
      - '8888:80'
    networks:
      - sf-payments
  php:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
    container_name: php-sf-payments
    volumes:
      - './src:/var/www/html'
    networks:
      - sf-payments
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sf-payments-mysql-data:/var/lib/mysql'
    networks:
      - sf-payments
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
